async/await
Para aprender a realizar testes utilizando o async/await , voc√™ vai realizar uma requisi√ß√£o a API e testar o seu retorno em caso de sucesso e de falha.
Mas pera√≠, se eu vou realizar uma requisi√ß√£o para API para testar se ela est√° funcionando, o que acontece se ela estiver fora do ar?
Bem pensado! Ao fazer uma requisi√ß√£o para uma API, n√≥s dependemos de diversos fatores externos ao nosso c√≥digo, alguns exemplos s√£o ter acesso a internet e o servi√ßo da API funcionar... Ent√£o, tenha em mente que:
Voc√™ nunca deve testar uma requisi√ß√£o real para a API!
Imagine que voc√™ est√° utilizando uma API da previs√£o do tempo, no momento da cria√ß√£o do seu teste a previs√£o era de sol. No dia seguinte voc√™ vai dar continuidade para os testes, mas agora a API est√° retornando que a previs√£o √© de chuva, ou seja, o teste passava enquanto a previs√£o era sol, quando passou a ser chuva, seu teste falhou. Al√©m da falta de controle sobre o retorno de uma requisi√ß√£o, voc√™ tamb√©m pode ter problemas como:
A URL da API estar incorreta.
Uma falha na conex√£o com a internet.
Uma instabilidade no servidor que gerencia a API.
Se nunca podemos testar nossa fun√ß√£o com uma API real, ent√£o como podemos realizar os testes?
Lembra que ali em cima comentamos que o Jest nos oferece diversas ferramentas para testarmos nosso c√≥digo? Uma dessas ferramentas √© a simula√ß√£o na execu√ß√£o da fun√ß√£o, podendo definir o retorno que ela ter√°. Dessa forma, voc√™ consegue controlar diversos cen√°rios, como sucesso e falha.
N√£o se preocupe em entender agora como essa simula√ß√£o √© criada, voc√™ vai aprender a criar essas simula√ß√µes no m√≥dulo de Front-end, quando for trabalhar com testes em React. O objetivo do dia de hoje √© entender como realizar testes em fun√ß√µes ass√≠ncronas, combinado?
Para acompanhar o dia, disponibilizamos um reposit√≥rio com a simula√ß√£o pronta para que voc√™ possa focar no conte√∫do de hoje, que s√£o testes ass√≠ncronos. Atente-se apenas ao arquivo fetchCharacter.js , que √© respons√°vel pela requisi√ß√£o e ao arquivo de teste fetchCharacter.test.js , que √© o √∫nico arquivo a ser alterado, tudo bem? Siga o passo a passo do Readme para realizar o fork do reposit√≥rio e executar a aplica√ß√£o.
A API que ser√° usada √© a Superhero API , que possui como par√¢metro um token , que funciona como uma senha para possibilitar o uso da API e um id ( https://www.superheroapi.com/api.php/TOKEN/ID ). O token j√° est√° configurado, portanto, a √∫nica informa√ß√£o que a ser passada para a fun√ß√£o fetchCharacter √© o id .
Ao abrir o arquivo fetchCharacter.js , voc√™ vai perceber que ele possui duas fun√ß√µes: uma com async/await e outra com .then() , que est√° comentada. O motivo para isso √© apenas para voc√™ ter nitidez que pode utilizar e escolher qualquer uma das duas formas.
Voc√™ buscar√° um super her√≥i por meio do id que √© passado na URL, e o retorno ser√° um objeto contendo o super her√≥i correspondente e os seus atributos.
A url base a ser utilizada √© https://www.superheroapi.com/api.php/4192484924171229/720 , que ir√° retornar uma personagem.
Nosso primeiro passo √© estruturar o bloco de teste com async/await . Cada bloco aceita dois par√¢metros, o primeiro √© a descri√ß√£o do que est√° sendo testado e o segundo √© uma fun√ß√£o an√¥nima, ou seja, sem nome. A estrutura inicial fica assim:
Copiar
  it('descri√ß√£o', () => {});
Para testar c√≥digo ass√≠ncrono, √© preciso fazer uso do async/await . Para isso, adicione o async antes da fun√ß√£o an√¥nima e o await no momento em que chamar a requisi√ß√£o. Veja:
Copiar
  it('descri√ß√£o', async () => {
    await requisicao();
  });
Para organizar melhor seus testes, voc√™ pode utilizar o describe , que serve justamente para descrever, de forma geral, o que seu arquivo est√° fazendo:
Copiar
  describe('descri√ß√£o geral', () => {
    it('descri√ß√£o', async () => {
      await requisicao();
    });
  });
Agora que voc√™ j√° tem a estrutura, vamos p√¥r a m√£o na massa!
O primeiro teste ser√° para verificar qual o nome da personagem. Mas, para isso, √© preciso saber como √© a estrutura de resposta da API utilizando um console.log() :
Utilize o id 720 .
Copiar
  it('Verifica se o nome da personagem √© Wonder Woman', async () => {
    const character = await fetchCharacter('720');
    console.log(character);
  });
A resposta da API √© um objeto, certo? E, se voc√™ precisar testar o nome da personagem, pode acessar a chave name desse objeto, ou seja character.name .

Log do objeto
Copiar
  it('Verifica se o nome da personagem √© Wonder Woman', async () => {
    const character = await fetchCharacter('720');
    console.log(character.name);
  });
No terminal aparece o nome da nossa personagem: Wonder Woman .

Log do nome da personagem
Agora implemente o teste:
Copiar
  it('Verifica se o nome da personagem √© Wonder Woman', async () => {
    const character = await fetchCharacter('720');
    expect(character.name).toBe('Wonder Woman');
  });
Eba! O teste passou! Mas para garantir que est√° tudo certo, √© preciso verificar se n√£o √© um falso positivo. Para isso, altere o resultado esperado por Spider Man .
Copiar
  it('Verifica se o nome da personagem √© Wonder Woman', async () => {
    const character = await fetchCharacter('720');
    expect(character.name).toBe('Spider Man');
  });
O teste falhou, isso significa que voc√™ n√£o possui um falso positivo!
Volte o resultado esperado para Wonder Woman .
Boa! Voc√™ testou um caso de sucesso na requisi√ß√£o da API, certo? Agora, √© preciso testar um cen√°rio de erro ao executar a fun√ß√£o sem nenhum par√¢metro.
Siga o mesmo processo anterior, observando o retorno da requisi√ß√£o pelo console.log() :
Copiar
  it('Verifica se retorna erro ao executar a fun√ß√£o sem par√¢metro', async () => {
    const failRequest = await fetchCharacter();
    console.log(failRequest);
  });
Apareceu um erro no seu terminal, certo? üëª
N√£o se preocupe se o texto do erro for grande, observe a primeira linha:

Log do erro 'You must provide an url'
Perceba que na primeira linha do erro aparece o seguinte:
Error: "You must provide an url"
Esse erro √© lan√ßado pela requisi√ß√£o e, para testar esse cen√°rio, √© necess√°rio reproduzir esse objeto de erro criado quando a promise foi rejeitada.
Informe ao teste que o esperado √© que a requisi√ß√£o retorne um erro que possua o texto 'You must provide an url'.
Copiar
  it('Verifica se retorna erro ao executar a fun√ß√£o sem par√¢metro', async () => {
    const failRequest = await fetchCharacter();

    expect(failRequest).toEqual(new Error('You must provide an url'));
  });
Como voc√™ pode notar, foi utilizado o new Error , que √© um construtor do JavaScript respons√°vel por criar um objeto de erro. Ao testar a falha da requisi√ß√£o, estamos comparando o erro lan√ßado pelo teste com o erro lan√ßado pela requisi√ß√£o.
Voc√™ vai se aprofundar no que √© um construtor no m√≥dulo de Ci√™ncia da Computa√ß√£o
At√© aqui foi testado o resultado da requisi√ß√£o, mas como testar o valor da promise, ou seja, esperar que a promise seja resolvida ou rejeitada? Existem dois matchers, o resolves e o rejects que fazem o teste direto na promise, d√° uma olhada nesse v√≠deo aqui üëá

Bom, at√© agora voc√™ testou os cen√°rios de sucesso e de falha da requisi√ß√£o, correto? O sucesso acontece quando √© passado o par√¢metro esperado e a falha quando n√£o √© passado par√¢metro algum. Mas o que acontece se utilizar um par√¢metro estranho, ou seja, quando a url receber alguma informa√ß√£o que n√£o existe?
Tenha em mente que cada API trata erros de forma diferente. Por isso, sempre leia a documenta√ß√£o e use o console.log() para ver os retornos.
Primeiro verifique o que a API retorna e para isso vamos utiilize o console.log() ;
Copiar
  it('Verifica se retorna \'Invalid id\' ao executar a fun√ß√£o com par√¢metro que n√£o existe', async () => {
    const response = await fetchCharacter('parametro qualquer');
    console.log(response);
  });
Perceba que o retorno do console foi esse:

Log do erro 'Invalid id'
Ou seja, quando √© passado um id inv√°lido como par√¢metro da fun√ß√£o, o retorno √© Invalid id .
Ent√£o vamos ao teste:
Copiar
  it('Verifica se retorna \'Invalid id\' ao executar a fun√ß√£o com par√¢metro que n√£o existe', async () => {
    const response = await fetchCharacter('parametro qualquer');
    expect(response).toBe('Invalid id');
  });
Verifique se o teste n√£o √© um falso positivo, para isso troque o texto Invalid id por Erro . Se o teste falhar, significa que n√£o √© um falso positivo.
Foi testado tr√™s poss√≠veis casos:
quando nosso id est√° correto
quando n√£o passamos id algum
quando ele √© incorreto.
Agora, para finalizar, √© necess√°rio testar a chamada da fun√ß√£o e se a url recebida √© a correta. Para isso, √© preciso executar a fun√ß√£o fetchCharacter , mas nesse caso, √© necess√°rio 'esperar' que a fun√ß√£o fetch seja chamada 4 vezes e tamb√©m se √© executada com o par√¢metro correto:
Copiar
  it('Verifica se fetch √© chamada com o endpoint correto', async () => {
    const url = 'https://www.superheroapi.com/api.php/4192484924171229/720';
    await fetchCharacter('720');
    expect(fetch).toHaveBeenCalledTimes(4);
    expect(fetch).toHaveBeenCalledWith(url);
  });
Por que precisamos testar o fetch nessa situa√ß√£o?
A fun√ß√£o fetchCharacter √© respons√°vel por receber o id e passar para a fun√ß√£o fetch . √â a fetch que executa a requisi√ß√£o a partir da url e s√≥ ent√£o a fetchCharacter retorna o resultado. Os 3 primeiros testes conferiram o resultado da requisi√ß√£o, no √∫ltimo teste, foi verificado, de fato, a implementa√ß√£o da fun√ß√£o que executa a requisi√ß√£o, ou seja, testar se fetch foi chamada 4 vezes (executamos a fun√ß√£o uma vez para cada teste realizado) e verificar se, no √∫ltimo teste, foi chamada com a url correta para buscar os dados na API. Note que, ao utilizar o matcher toHaveBeenCalledTimes , ele verificou quantas vezes a fun√ß√£o fetch foi executada dentro de todo o describe , ou seja, vazou do escopo. Para evitar esse tipo de problema, voc√™ pode utilizar o beforeEach ou o afterEach .
Pausa para aquele cafezinho e partiu p√¥r a m√£o na massa!
coffee
